repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-xml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
- repo: https://github.com/nineyards-robotics/dco-sign-off
  rev: v1.0.0
  hooks:
  - id: dco-sign-off
